config/routes.rb
Rails.application.routes.draw do
  resources :candidates, only: :index do
    post :check, on: :collection
  end

  root to: 'candidates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :candidate_creations

  def import_candidates!(data)
    candidate_creations.create(data).tap do |results|
      import_candidates_failure! nil, count: results.size
    end
  end

  def import_candidates_failure!(failure, count: 0, at: DateTime.current)
    update import_candidates_failure: failure,
           import_candidates_count: count,
           import_candidates_at: at
  end

  delegate :count, to: :candidate_creations, prefix: true
end

app/models/candidate_creation.rb
class CandidateCreation < ApplicationRecord
  belongs_to :campaign

  def response=(response)
    self.response_code = response.code
    self.response_body = response.body
  end

  def ok?
    response_code == 200
  end
end

app/models/candidate_details.rb
CandidateDetails = Struct.new(:timestamp, :first_name, :last_name, :email, :phone_number) do
  def initialize(timestamp, *columns)
    super(DateTime.strptime(timestamp, "%m/%d/%Y %H:%M:%S"), *columns)
  rescue
    super
  end

  def self.to_proc
    -> row { new *row }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action -> { @campaign = Campaign.last }

  def index
    @campaign = CampaignPresenter.new(@campaign, view_context)
    @candidates = @campaign.candidate_creations.map(&CandidatePresenter)

    if @campaign.import_candidates_failure?
      flash.alert = "Checking Failed: #{@campaign.import_candidates_failure_message}"
    end
  end

  def check
    ImportNewCandidatesJob.perform_later @campaign

    redirect_to root_path, notice: 'Checking Candidates. Reload this page to see changes.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1><%= @campaign.name %></h1>

<table>
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Response</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.timestamp.to_s(:db) %></td>
        <td><%= candidate.first_name %></td>
        <td><%= candidate.last_name %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.phone_number %></td>
        <td><%= candidate.response_message %></td>
        <td><%= candidate.status %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td><%= button_to 'Check Candidates', check_candidates_path, method: :post %></td>
      <td colspan="4">
        Last check was <%= @campaign.last_import_in_words %> with <%= @campaign.import_candidates_count %> new candidate(s).
      </td>
      <td colspan="2"><%= @campaign.candidate_creations_count %> total candidates</td>
    </tr>
  </tfoot>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExerciseRitchieBuitre</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>